/*
PROYECTO #2 - BATALLA NAVAL
INGENIERIA EN COMPUTACION
INSTITUTO TECNOLOGICO DE COSTA RICA
PROGRAMACION ORIENTADA A OBJETOS
II SEMESTRE 2019
INTEGRANTES: 
            -ALEXANDER ARTAVIA QUESADA
            -JOAN SANCHEZ CHINCHILLA
            -ARMANDO CASTRO RUIZ
PROFESORA:
            -SAMANTA RAMIJAN
*/


package proyecto2_batallanaval;

/**
 *
 * @author Joan
 */
public class MenuInicioFrame extends javax.swing.JFrame {
    //Se crean los objetos necesarios para crear los tableros graficos
    TableroDePosicion TDP_J1 = new TableroDePosicion();
    TableroPrincipal TP_J1 = new TableroPrincipal();
    TableroDePosicion TDP_J2 = new TableroDePosicion();
    TableroPrincipal TP_J2 = new TableroPrincipal();
    TableroDeJugador1 t1 = new TableroDeJugador1();
    TableroDeJugador2 t2 = new TableroDeJugador2();
    ComoJugarFrame info = new ComoJugarFrame();
    
    public MenuInicioFrame() {
        initComponents();
        this.setLocationRelativeTo(null);   //ASI SE PONE LA VENTANA CENTRADA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msjSalir = new javax.swing.JButton();
        comenzarPartidaButton = new javax.swing.JButton();
        msjComoJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                 MENU PRINCIPAL");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        msjSalir.setBackground(new java.awt.Color(255, 0, 0));
        msjSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        msjSalir.setText("Salir");
        msjSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msjSalirActionPerformed(evt);
            }
        });
        getContentPane().add(msjSalir);
        msjSalir.setBounds(420, 230, 160, 40);

        comenzarPartidaButton.setBackground(new java.awt.Color(0, 204, 51));
        comenzarPartidaButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comenzarPartidaButton.setText("Comenzar Partida");
        comenzarPartidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarPartidaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(comenzarPartidaButton);
        comenzarPartidaButton.setBounds(10, 190, 160, 40);

        msjComoJugar.setBackground(new java.awt.Color(204, 204, 0));
        msjComoJugar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        msjComoJugar.setText("¿Cómo Jugar?");
        msjComoJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msjComoJugarActionPerformed(evt);
            }
        });
        getContentPane().add(msjComoJugar);
        msjComoJugar.setBounds(10, 250, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectImages/BatallaNavalMenu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msjSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msjSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_msjSalirActionPerformed
    
    //Metodo que comienza la partida creando los tableros graficos
    private void comenzarPartidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarPartidaButtonActionPerformed

        t1.TDP = TDP_J1;
        t1.TP = TP_J1;
        t1.TP.TDP = TDP_J2;
        t1.setTableroJugadorRival(t2);
        t1.setTableroPropio(t1);
        
        
        t2.TDP = TDP_J2;
        t2.TP = TP_J2;
        t2.TP.TDP = TDP_J1;
        t2.setTableroJugadorRival(t1);
        t2.setTableroPropio(t2);
        
        t1.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_comenzarPartidaButtonActionPerformed
    //Metodo que muestra al usuario una ayuda de como jugar al oprimir el boton
    private void msjComoJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msjComoJugarActionPerformed
        info.setVisible(true);
        
    }//GEN-LAST:event_msjComoJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comenzarPartidaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton msjComoJugar;
    private javax.swing.JButton msjSalir;
    // End of variables declaration//GEN-END:variables
}
